# https://dzone.com/articles/a-simple-checklist-for-apache-ignite-beginners
# discovery port 47500
version: "3.9"
services:
  ignite01:
    image: apacheignite/ignite:2.13.0-jdk11
    volumes:
      - ./ignite-config.xml:/ignite-config.xml:ro
    ports:
      - "10800:10800"
    environment:
      - CONFIG_URI=/ignite-config.xml
    #   - IGNITE_TCP_DISCOVERY_ADDRESSES=ignite02,ignite03
  ignite02:
    image: apacheignite/ignite:2.13.0-jdk11
    volumes:
      - ./ignite-config.xml:/ignite-config.xml:ro
    ports:
      - "10801:10800"
    environment:
      - CONFIG_URI=/ignite-config.xml
    #   - IGNITE_TCP_DISCOVERY_ADDRESSES=ignite01,ignite03
  ignite03:
    image: apacheignite/ignite:2.13.0-jdk11
    volumes:
      - ./ignite-config.xml:/ignite-config.xml:ro
    ports:
      - "10802:10800"
    environment:
      - CONFIG_URI=/ignite-config.xml
    #   - IGNITE_TCP_DISCOVERY_ADDRESSES=ignite01,ignite02
  # console:
  #   image: apacheignite/web-console-standalone:2.7.0
  #   ports:
  #     - "80:80"
  #     - "3001:3001"
  ignite-activate:
    image: apacheignite/ignite:2.13.0-jdk11
    depends_on:
      - ignite01
      - ignite02
      - ignite03
    command: "bash -c \"sleep 10 && /opt/ignite/apache-ignite/bin/control.sh --host ignite01 --set-state ACTIVE --yes\""
